brew "stow"
brew "asdf"
brew "coreutils"
brew "gpg"
brew "gawk"
brew "bash"
brew "bash-completion"
brew "nvim"
brew "tmux"
brew "curl"
brew "wget"
brew "nmap"
brew "watch"
brew "fd"
brew "fzf"
brew "bat"
brew "starship"
brew "rg"
brew "autojump"
brew "tree"
brew "tealdeer"
brew "vips"
brew "mas"
brew "imagemagick"
brew "lua-language-server"
brew "yaml-language-server"
brew "typescript-language-server"
brew "prettier"
brew "peterldowns/tap/localias"

cask "ghostty"
cask "rectangle"
cask "dash"
cask "raycast"
cask "cleanshot"
cask "tableplus"
cask "zed"
cask "ticktick"

mas "Theine", id: 955848755
mas "Kindle", id: 302584613
