#!/bin/bash

RED="31"
GREEN="32"
BOLDGREEN="\033[1;${GREEN}m"
BOLDRED="\033[1;${RED}m"
ENDCOLOR="\033[0m"

ERRORS=()

# helper functions
progress_message() {
  printf "${BOLDGREEN}$1${ENDCOLOR}"
}

error_message() {
  printf "${BOLDRED}$1${ENDCOLOR}" >> /dev/stderr
}

execute_command() {
  progress_message "${2}..."

  error=$($1 2>&1)

  if [ $? -eq 0 ]; then
    progress_message " Ok!\n"
  else
    error_message " Fail!\n"
    ERRORS+=("> $1\n${error}\n\n")
  fi
}

# Check for Homebrew to be present, install if it's missing
if test ! $(which brew); then
  progress_message "> Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Install Homebrew packages
execute_command "brew bundle"

# Setup login shell from homebrew
BREW_PREFIX="$(brew --prefix)"
NEW_SHELL="$BREW_PREFIX/bin/bash"

if ! grep -Fxq "$NEW_SHELL" /etc/shells; then
  echo "$NEW_SHELL" | sudo tee -a /etc/shells
fi

chsh -s "$NEW_SHELL"

# Check for tmux/tpm to be present, install if it's missing
if [ -d "~/.tmux/plugins/tpm" ]; then
  execute_command "git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm" \
    "> Installing Tmux Package Manager"
fi

if [ ${#ERRORS[@]} -gt 0 ]; then
  printf "\n${BOLDRED}The following errors occurred:${ENDCOLOR}\n"
  printf "%b" "${ERRORS[@]}"
fi
