#!/bin/bash

RED="31"
GREEN="32"
BOLDGREEN="\033[1;${GREEN}m"
BOLDRED="\033[1;${RED}m"
ENDCOLOR="\033[0m"

ERRORS=()

# helper functions
progress_message() {
  printf "${BOLDGREEN}$1${ENDCOLOR}"
}

error_message() {
  printf "${BOLDRED}$1${ENDCOLOR}" >> /dev/stderr
}

execute_command() {
  progress_message "${2}..."

  error=$($1 2>&1)

  if [ $? -eq 0 ]; then
    progress_message " Ok!\n"
  else
    error_message " Fail!\n"
    ERRORS+=("> $1\n${error}\n\n")
  fi
}

# Check for Homebrew to be present, install if it's missing
if test ! $(which brew); then
  progress_message "> Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Brew packages
PACKAGES=(
  asdf
  coreutils
  gpg
  gawk
  bash-completion
  nvim
  tmux
  curl
  wget
  nmap
  watch
  fd
  fzf
  bat
  starship
  rg
  autojump
  tree
  tealdeer
  postgresql@16
)

execute_command "brew update --quiet" "> Updating list of homebrew packages"
execute_command "brew install --quiet ${PACKAGES[*]}" "> Installing homebrew packages"

# Check for tmux/tpm to be present, install if it's missing
if [ -d "~/.tmux/plugins/tpm" ]; then
  execute_command "git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm" \
    "> Installing Tmux Package Manager"
fi

# Install key-bindings and fuzzy completion for FZF
if which fd >/dev/null 2>&1; then
  execute_command "/usr/local/opt/fzf/install --xdg --completion --key-bindings --no-update-rc --no-bash --no-zsh --no-fish" \
    "> Installing key-bindings and fuzzy completion for FZF"
fi

if [ ${#ERRORS[@]} -gt 0 ]; then
  printf "\n${BOLDRED}The following errors occurred:${ENDCOLOR}\n"
  printf "%b" "${ERRORS[@]}"
fi
